### ISSUE TITLE
Genome fasta downloading issue

### ISSUE THREAD

**Issue by JackSun1997** [NBChub/bgcflow#249]
Hello Martin, during running the pipeline I have some issues with downloading NCBI fasta file for my samples. All samples downloading fail with the errors(I will give one of them as an example): 

`Traceback (most recent call last):
  File "/mnt/pankb_ale/bgcflow/.snakemake/conda/a7741b92e8354497f5d9a4ef0b351f0c_/bin/ncbi-genome-download", line 10, in <module>
    sys.exit(main())
  File "/mnt/pankb_ale/bgcflow/.snakemake/conda/a7741b92e8354497f5d9a4ef0b351f0c_/lib/python3.9/site-packages/ncbi_genome_download/__main__.py", line 26, in main
    ret = args_download(args)
  File "/mnt/pankb_ale/bgcflow/.snakemake/conda/a7741b92e8354497f5d9a4ef0b351f0c_/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 178, in args_download
    return config_download(config)
  File "/mnt/pankb_ale/bgcflow/.snakemake/conda/a7741b92e8354497f5d9a4ef0b351f0c_/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 197, in config_download
    download_candidates = select_candidates(config)
  File "/mnt/pankb_ale/bgcflow/.snakemake/conda/a7741b92e8354497f5d9a4ef0b351f0c_/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 308, in select_candidates
    for entry in filter_entries(entries, config):
  File "/mnt/pankb_ale/bgcflow/.snakemake/conda/a7741b92e8354497f5d9a4ef0b351f0c_/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 354, in filter_entries
    if not config.is_compatible_assembly_accession(entry['assembly_accession']):
KeyError: 'assembly_accession'`

**Comment by matinnuhamunada** [comment]
This is related to this issue: https://github.com/kblin/ncbi-genome-download/issues/209
A PR is underway: https://github.com/kblin/ncbi-genome-download/pull/210
