### ISSUE TITLE
CheckM fails to parse numpy float64 binStats results

### ISSUE THREAD

**Issue by matinnuhamunada** [NBChub/bgcflow#350]
CheckM fails to parse numpy float64 binStats results and gave this error:

```bash
Unexpected error: <class 'ValueError'>
Traceback (most recent call last):
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/site-packages/checkm/main.py", line 980, in parseOptions
    self.lineageSet(options)
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/site-packages/checkm/main.py", line 249, in lineageSet
    resultsParser.analyseResults(options.tree_dir,
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/site-packages/checkm/resultsParser.py", line 63, in analyseResults
    binStats = self.parseBinStats(outDir, binStatsFile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/site-packages/checkm/resultsParser.py", line 156, in parseBinStats
    binStats[lineSplit[0]] = ast.literal_eval(lineSplit[1])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/ast.py", line 108, in literal_eval
    return _convert(node_or_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/ast.py", line 97, in _convert
    return dict(zip(map(_convert, node.keys),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/ast.py", line 107, in _convert
    return _convert_signed_num(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/ast.py", line 81, in _convert_signed_num
    return _convert_num(node)
           ^^^^^^^^^^^^^^^^^^
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/ast.py", line 72, in _convert_num
    _raise_malformed_node(node)
  File "/home/matinnu/test/bgcflow/.snakemake/conda/9155ccccbb351d3788fd4776665701e0_/lib/python3.11/ast.py", line 69, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Call object at 0x7fd1bf216740>
```

Which is caused by using ast.literal to read this string:
`{'GC': 0.49686340673501883, 'GC std': 0.0, 'Genome size': 1856951, '# ambiguous bases': 0, '# scaffolds': 1, '# contigs': 1, 'Longest scaffold': 1856951, 'Longest contig': 1856951, 'N50 (scaffolds)': 1856951, 'N50 (contigs)': 1856951, 'Mean scaffold length': np.float64(1856951.0), 'Mean contig length': np.float64(1856951.0), 'Coding density': 0.8387221849149493, 'Translation table': 11, '# predicted genes': 1920}`

Related to: https://github.com/Ecogenomics/CheckM/issues/396

**Comment by matinnuhamunada** [comment]
Fixed in ce299f0dd2cdee066cb415d02aa46bbb0d459de4
